from decouple import config

FIREBASE_PROJECT_ID = config('FIREBASE_PROJECT_ID')
FIREBASE_PRIVATE_KEY_ID = config('FIREBASE_PRIVATE_KEY_ID')
FIREBASE_PRIVATE_KEY = config('FIREBASE_PRIVATE_KEY').replace("\\n", "\n")
FIREBASE_CLIENT_EMAIL = config('FIREBASE_CLIENT_EMAIL')
FIREBASE_CLIENT_ID = config('FIREBASE_CLIENT_ID')
FIREBASE_AUTH_URI = config('FIREBASE_AUTH_URI')
FIREBASE_TOKEN_URI = config('FIREBASE_TOKEN_URI')
FIREBASE_AUTH_PROVIDER_CERT_URL = config('FIREBASE_AUTH_PROVIDER_CERT_URL')
FIREBASE_CLIENT_CERT_URL = config('FIREBASE_CLIENT_CERT_URL')
FIREBASE_UNIVERSE_DOMAIN = config('FIREBASE_UNIVERSE_DOMAIN')
